### ISSUE TITLE
Consider detecting and running prettier if the repo supports it after committing to eik.json

### ISSUE THREAD

**Issue by digitalsadhu** [eik-lib/cli#154]
Not doing so can mean builds fail when linting/prettier runs

**Comment by wkillerud** [comment]
Prettier can be [configured to ignore](https://prettier.io/docs/en/ignore) `eik.json`. In my experience you typically want to set up such ignores for files that are fully or partially machine generated (including `package.json`). I think it's fine to go without this.

Since the issue is a few years old I'll close it as not planned.
